# Generated by Django 3.1.6 on 2021-12-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('faculty', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish', models.CharField(max_length=255)),
                ('direction', models.CharField(max_length=255)),
                ('edu_type', models.CharField(max_length=255)),
                ('lang', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=10)),
                ('subject', models.ManyToManyField(related_name='exam_subjects', to='studentExam.Subject')),
            ],
        ),
    ]
