# Generated by Django 3.1.6 on 2021-12-18 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentExam', '0003_auto_20211218_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='edu_type',
        ),
        migrations.RemoveField(
            model_name='student',
            name='lang',
        ),
    ]
