# Generated by Django 3.1.6 on 2021-12-18 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentExam', '0004_auto_20211218_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='course',
            new_name='group',
        ),
    ]
