"""
Django settings for projectroot project.

Generated by 'django-admin startproject' using Django 3.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
from projectroot.credentianls import *


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = secret_key

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = debug

ALLOWED_HOSTS = allowed_hosts

# Application definition

INSTALLED_APPS = [
    'jet.dashboard',
    'jet',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'rest_framework', # django-rest-framework
    'tinymce',
    'phonenumber_field',
    'smart_selects',
    'import_export',
    
    'apps.blog.apps.BlogConfig',
    'apps.core.apps.CoreConfig',
    'apps.drf_docs.apps.DrfDocsConfig',
    'apps.signals_django.apps.SignalsDjangoConfig',
    'apps.users.apps.UsersConfig',
    'apps.django_import_export.apps.DjangoImportExportConfig',
    "apps.studentExam.apps.StudentexamConfig",
    "apps.tryDrf.apps.TrydrfConfig",
    "apps.jetReboot.apps.JetrebootConfig",
    # 'apps.django_celery.apps.DjangoCeleryConfig',
]

AUTH_USER_MODEL = 'users.CustomUserModel'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'projectroot.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'projectroot.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': db_engine,
        'NAME': BASE_DIR / db_name,
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static_root/'

staticfiles_dirs = BASE_DIR / 'static/'
STATICFILES_DIRS = [
    staticfiles_dirs,
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media_root'


# smpt gmail stuff
EMAIL_BACKEND       = email_backend
EMAIL_USE_TLS       = email_use_tls
EMAIL_HOST          = email_host
EMAIL_HOST_USER     = email_host_user
EMAIL_HOST_PASSWORD = email_host_password
EMAIL_PORT          = email_port

# CELERY STUFF
# BROKER_URL               = 'redis://127.0.0.1:6379' # broker for message transport
# CELERY_RESULT_BACKEND    = 'redis://127.0.0.1:6379' # result backend
# CELERY_ACCEPT_CONTENT    = ['application/json']
# CELERY_TASK_SERIALIZER   = 'json'
# CELERY_RESULT_SERIALIZER = 'json'
# CELERY_TIMEZONE          = 'Asia/Tashkent'
